name: Build & Zip (.NET)

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: "9.0.x"                 # Change if you target a different SDK
  SOLUTION_PATH: "MareSynchronos.sln"          # ← set to your .sln
  PROJECT_PATH: "MareSynchronos/MareSynchronos.csproj"  # <- << SET THIS to your .csproj path
  CONFIGURATION: "Release"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive           # ← important if API/shared is a submodule
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Dalamud runtime for the SDK check
      - name: Fetch Dalamud runtime for CI
        run: |
          set -e
          wget -q https://goatcorp.github.io/dalamud-distrib/latest.zip
          mkdir -p dalamud
          unzip -q latest.zip -d dalamud
          echo "DALAMUD_HOME=$PWD/dalamud" >> $GITHUB_ENV

      - name: Restore (solution)
        run: dotnet restore "${{ env.SOLUTION_PATH }}"

      - name: Build (solution)
        run: dotnet build "${{ env.SOLUTION_PATH }}" -c "${{ env.CONFIGURATION }}" --no-restore

      - name: Pack plugin
        run: dotnet build "${{ env.SOLUTION_PATH }}" -c "${{ env.CONFIGURATION }}" -p:GenerateDalamudZip=true
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/bin/Release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}